### ISSUE TITLE
Requesting admin access to Azure repos

### ISSUE THREAD

**Issue by Hong-Revo** [cloudyr/cloudyr.github.io#24]
Hi @MarkEdmondson1234, when I migrated my Azure repos to cloudyr, it gave me write access. Would it be possible to set this to admin access? I need this to add collaborators, manage topics, migrate issues and so on.

The affected repos are [AzureRMR](../../AzureRMR), [AzureVM](../../AzureVM), [AzureStor](../../AzureStor) and [AzureContainers](../../AzureContainers).

Thanks!

**Comment by MarkEdmondson1234** [comment]
Hi @Hong-Revo :)

I added those repos to the Azure team here: https://github.com/orgs/cloudyr/teams/azure-packages/repositories so that should be done, can you check?  In the future any other Azure repos should be added to this team for similar access, and if other users want access add them to the team.

**Comment by Hong-Revo** [comment]
Yep, it's working fine. Thanks!
